return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",

  config = function()
    local treesitter = require("nvim-treesitter")

    treesitter.setup({
      install_dir = vim.fn.stdpath("data") .. "/site",
    })

    treesitter.install({
      "bash",
      "bibtex",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "csv",
      "diff",
      "editorconfig",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "glsl",
      "hjson",
      "hlsl",
      "html",
      "html_tags",
      "htmldjango",
      "http",
      "ini",
      "java",
      "javadoc",
      "javascript",
      "jinja",
      "jinja_inline",
      "jsdoc",
      "json",
      "json5",
      "jsonnet",
      "latex",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "matlab",
      "nginx",
      "perl",
      "printf",
      "pymanifest",
      "python",
      "r",
      "rasi",
      "readline",
      "regex",
      "requirements",
      "robot",
      "robots_txt",
      "rust",
      "scss",
      "ssh_config",
      "superhtml",
      "todotxt",
      "toml",
      "udev",
      "vim",
      "vimdoc",
      "wgsl",
      "wgsl_bevy",
      "xml",
      "xresources",
      "yaml",
      "zathurarc",
      "zsh",
    })
  end,
}
