general.import = [
  "/home/bubu/.config/alacritty/themes/tokyonight.toml"
]
[window]
padding.x = 10
padding.y = 10

[font]
normal.family = "MesloLGS NF"
normal.style = "Regular"

bold.family = "MesloLGS NF"
bold.style = "Bold"

italic.family = "MesloLGS NF"
italic.style = "Italic"

bold_italic.family = "MesloLGS NF"
bold_italic.style = "Bold Italic"

size = 12
